version: '3'

services:
  database:
    image: postgres:latest
    container_name: database
    restart: always
    env_file:
      - postgres.env
    volumes:
      - db-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  backend:
    build: ./server/
    image: woody-lam-cwl/full-stack-python
    container_name: backend
    restart: always
    ports:
      - 8000:8000

  frontend:
    build: ./app/
    image: woody-lam-cwl/full-stack-react
    container_name: frontend
    restart: always
    ports:
      - 3000:3000
    expose:
      - '3000'

volumes:
  db-data:
